variable "project_name" {
  type = string
}

variable "environment" {
  type = string
}

variable "subnet_id" {
  description = "Private/protected subnet the instances live in"
  type        = string
}

variable "security_group_id" {
  type = string
}

variable "iam_instance_profile" {
  type = string
}

variable "ssh_public_key" {
  description = "Public half of a keypair generated by hand (ssh-keygen); see ../../envs/dev/variables.tf"
  type        = string
}

variable "instances" {
  description = <<-EOT
    App servers to create, keyed by a short identifier (e.g. "1", "2"). The
    key becomes part of the resource's Name tag. Every field is optional —
    add another entry (or override a field) and re-apply to scale; that's
    the whole "scale path", no ASG required.

    Optional per entry:
      instance_type - EC2 instance type (default: t3.micro)
      volume_size   - root volume size in GB (default: 12)
  EOT
  type = map(object({
    instance_type = optional(string, "t3.micro")
    volume_size   = optional(number, 12)
  }))
  default = {
    "1" = {}
  }
}
